### PR TITLE
eSCL is not advertised

### PR DESCRIPTION
**Pull request by ThierryHFR**
Try to solve the issue #34 
Authentication has been removed.
The request is still made in clear text.
HEAD requests are deleted
Thanks to @alexpevzner  for these ideas

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Thank you for the patch.
It should not be a security problem to poll the scanner capabilities unencrypted, as we do not have confidential data of the user, but data which is part of a published hardware device, it is the same in each copy of this model.
Has someone suffering issue #34 already tested it?

**Comment by alexpevzner** [comment]
@tillkamppeter,

this is communication internal communication between `ippusbxd` and the device over USB. It cannot be encrypted.

In theory, there can be HTTP-level authentication. But I don't believe it is used in practice, because it is hard to imagine how usable logistics of authentication credentials to the IPP-over-USB daemon can be implemented.

**Comment by tangyanli** [comment]
@Ordissimo 
I tested the  Ordissimo:master this morning.
The issue still exists.
Here is the log.

[ippusbxd_ordissimo.log](https://github.com/OpenPrinting/ippusbxd/files/4654891/ippusbxd_ordissimo.log)

**Comment by ThierryHFR** [comment]
Thank you, rezerza,
We've moved on, this time the capabilities file is received.
I made a patch if you can test it?

**Comment by tangyanli** [comment]
@Ordissimo 
This is the log based on "Delete iteration GET request".
The issue still exists.

[ippusbxd_ordissimo_2.log](https://github.com/OpenPrinting/ippusbxd/files/4655506/ippusbxd_ordissimo_2.log)

**Comment by ThierryHFR** [comment]
Thank you very much @tangyanli !
Can you test again?

**Comment by tangyanli** [comment]
Ok, I will test it tomorrow. Hope it is fixed. :-)

**Comment by tangyanli** [comment]
@Ordissimo 
I tested it on Ubuntu20.04 & Debian10
eSCL is advertised well.
Thanks.

**Comment by ThierryHFR** [comment]
@tangyanli  Thanks for the tests!

@tillkamppeter  #34 is resolved:

**Comment by tillkamppeter** [comment]
Thank you very much for this pull request, I have merged it now.

**Pull request merged**
