### PR TITLE
Scanner detection correction.

### PR DESCRIPTION
**Pull request by ThierryHFR**

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Still does not find my scanner.

**Comment by tillkamppeter** [comment]
Added some debug lines to the is_ippusb_scanner() function, `interf->extra_length` never gets non-zero, so the main "if" does not get entered.

**Comment by ThierryHFR** [comment]
@tillkamppeter: Sorry, I didn't test,
I'm on vacation and I only have a canon mp250 printer that doesn't support AirPrint.
I'm testing tomorrow night!
Thierry

**Comment by tillkamppeter** [comment]
@Ordissimo, did you already test?

**Comment by ThierryHFR** [comment]
@tillkamppeter, 
1) parameters were not added to the _uscan._tcp entry, Fixed here : https://github.com/Ordissimo/ippusbxd/commit/afe9f5c3f0f461793a16488e2fbecbd2eab7b9c6
2)  I tested on a HP Deskjet 3750, a Brother DCP-L2530DW, a Epson ET-3750 and a Canon TS-3150.
None of them comply with the standard, the extra field never indicates the presence of a scanner.
I attached these two files for these devices because the USB port informs us of the presence of a scanner.
The other two I would join them tonight, they are on another site, but I have no info on the presence of a scanner.

[testCanonTS3150.txt](https://github.com/OpenPrinting/ippusbxd/files/4018430/testCanonTS3150.txt)
[testEpsonET3750.txt](https://github.com/OpenPrinting/ippusbxd/files/4018431/testEpsonET3750.txt)

**Comment by tillkamppeter** [comment]
The extra field is not supported by the `lsusb` tool and therefore is shown as unrecognized bytes, right after the `iInterface` entry of each IPP-over-USB (7/1/4) interface:
```
bInterfaceClass         7 Printer
bInterfaceSubClass      1 Printer
bInterfaceProtocol      4 
iInterface              0 
** UNRECOGNIZED:  0a 21 01 01 00 04 13 00 00 00
```
This is taken from the Epson ET 3750 and it shows that this device has a scanner. `wBasicCapabilities` is `13 00` here, the hex 13 is 00010011 bin, so bit 1, 2, and 5 are se, meaning printing, scanning, and admin interface.
The Canon does not have extra fields in the 7/1/4 interface descriptors.
How does the USB port of the Canon and Epson tell whether they have a scanner?

**Comment by tillkamppeter** [comment]
My HP DeskJet 2540 also does not have extra fields in the 7/1/4 interface descriptors.

**Comment by tillkamppeter** [comment]
The specification tells
> A device implementing IPP USB MUST provide the Device Info Descriptor described
below, and it must be structured in the way that is described in this section.

This means that if the extra field is missing from a 7/1/4 interface that it does not comply with the standard.

**Comment by tillkamppeter** [comment]
How did you obtain the attached files `testCanonTS3150.txt` and `testEpsonET3750.txt`? Which command lines you exactly used?

**Comment by tillkamppeter** [comment]
For me it looks like that the Device Info Descriptor method to determine whether the printer has a scanner or any other extra is not reliable as not all manufacturers comply with the standard here.
We could do a quick check whether a device supports eSCL scanning by checking the USB Device ID whether the device does AirPrint (supports URF as one of the PDLs) AND the Device Info Descriptor is present with the scanner bit set. This is a quick test and if positive, the printer does actually do eSCL scanning, but if it is negative the device can still support USB scanning.
My suggestion:
On startup of ippusbxd send HTTP requests to the device to check the presence of resources /ipp/print, /ipp/scan, and /eSCL. This determinse which services to advertise via DNS-SD, for filling the TXT records correctly, you need to poll the appropriate URIs for capabilities, get-printer-attributes IPP request for the first two and eSCL scanner capabilities request for the latter. With this one gets for sure correct info for the DNS-SD records.
For me it looks like that polling the Device Info Descriptor is not worthwhile. You can only get a bit whether a scanner is there, you have to poll the /eSCL (and /ipp/scan) resource anyway, to get a complete TXT record for nice listing of available scanners with basic capabilities in a menu, and also to check whether your scanner is eSCL, IPP Scan, or both.

**Comment by ThierryHFR** [comment]
> @tillkamppeter write : How did you obtain the attached files testCanonTS3150.txt and testEpsonET3750.txt? Which command lines you exactly used?

I used lsusb -vvv, I also looked with usbview, and debugged.

> @tillkamppeter write : My suggestion: On startup of ippusbxd ....

I agree, it's the most reliable.

**Comment by tillkamppeter** [comment]
@Ordissimo, you wrote:
> I used lsusb -vvv, I also looked with usbview, and debugged.

What do you mean with "and debugged" here? Is there some more verbose "debug" mode here?

**Comment by ThierryHFR** [comment]
No, there is no mode, I used NOTE() everywhere to check the set of values.
It was a failure.

**Pull request merged**
