### PR TITLE
Fix null fields.

### PR DESCRIPTION
**Pull request by ThierryHFR**
For the uuid can you send me the result of (ippusbxd --debug) ?
I've added log.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
This is the TXT record of the scanner part provided by ipp-usb:
```
HP OfficeJet Pro 8730 [08C229]: _uscan._tcp TXT record:
    duplex=F
    is=platen,adf
    cs=color,grayscale
    UUID=dbcc4b58-fc4c-f6fd-b4d6-2b00d554ad47
    adminurl=http://localhost:60000/#hId-pgAirPrint
    representation=http://localhost:60000/webApps/images/printer-small.png
    pdl=application/octet-stream,application/pdf,image/jpeg
    ty=HP OfficeJet Pro 8730
    rs=eSCL
    vers=2.5
    txtvers=1
```
The adminurl, UUID. and representation you can get from the get-printer-attributes IPP request on the printer part. Here is the printer part's TXT record of ipp-usb:
```
HP OfficeJet Pro 8730 [08C229]: _ipp._tcp TXT record:
    air=none
    mopria-certified=1.3
    rp=ipp/print
    priority=50
    kind=document,envelope,photo,postcard
    PaperMax=legal-A4
    URF=CP1,MT1-2-8-9-10-11,PQ3-4-5,RS300-600,SRGB24,OB10,W8,DEVW8,DEVRGB24,ADOBERGB24,DM3,FN3,IS1-2,V1.4
    UUID=dbcc4b58-fc4c-f6fd-b4d6-2b00d554ad47
    Color=T
    Duplex=T
    note=
    qtotal=1
    usb_MDL=HP OfficeJet Pro 8730
    usb_MFG=HP
    usb_CMD=PCL5c,PCLXL,POSTSCRIPT,NATIVEOFFICE,PDF,PCL3GUI,PCL3,PJL,Automatic,JPEG,PCLM,AppleRaster,PWGRaster,802.11,802.3,DESKJET,DYN
    ty=HP OfficeJet Pro 8730
    product=(HP OfficeJet Pro 8730)
    pdl=application/vnd.hp-PCL,application/vnd.hp-PCLXL,application/postscript,application/pdf,image/jpeg,application/PCLm,image/urf,image/pwg-raster,application/octet-stream
    txtvers=1
    adminurl=http://localhost:60000/#hId-pgAirPrint
```

**Comment by tillkamppeter** [comment]
This is the device ID of my device:
```
MFG:HP;MDL:HP OfficeJet Pro 8730;CMD:PCL5c,PCLXL,POSTSCRIPT,NATIVEOFFICE,PDF,PCL3GUI,PCL3,PJL,Automatic,JPEG,PCLM,AppleRaster,PWGRaster,802.11,802.3,DESKJET,DYN;CLS:PRINTER;DES:D9L20A;CID:HPIJVIPAV9;LEDMDIS:USB#FF#CC#00,USB#FF#04#01;MCT:MF;MCL:DI;MCV:3.0;SN:CN783F60W1;S:038080C484100001005800800004418003c451800464618003c41180046;Z:05000009000009000009000009000009,12000,17000000000000000000000000000000,181;
```

**Comment by ThierryHFR** [comment]
Did the TXT recording work?

**Comment by tillkamppeter** [comment]
Your pull request removed the "(null)" entries from the TXT record but fills them with items which do not really make sense.

**Comment by ThierryHFR** [comment]
the txt escl publication is functional. The HP Capabilities file does not provide all the information.
The problem of the infos not present, does not come from the eSCL detection, but from the lack of ipp infos.
I'm going to document myself and I'll complete in another pull-request.

**Comment by ThierryHFR** [comment]
I replaced curl by cups, I retrieve the missing info from the printer and add it to the TXT record.
The TXT scanner record is completed with the printer info if necessary.
It's fully functional.

**Comment by tillkamppeter** [comment]
And did you use the printer info also for the printer's TXT record?

**Comment by ThierryHFR** [comment]
Yes, I add UUID and adminurl.

**Comment by tillkamppeter** [comment]
ippusbxd is not able to parse my scanner capabilities, see attached file.
[log-20200211.txt](https://github.com/OpenPrinting/ippusbxd/files/4186501/log-20200211.txt)

**Comment by ThierryHFR** [comment]
Fix in : https://github.com/OpenPrinting/ippusbxd/pull/23

**Pull request merged**
