### PR TITLE
Fix memory overflow.

### PR DESCRIPTION
**Pull request by ThierryHFR**

### CODE REVIEW

**Review by tillkamppeter — APPROVED** [review]

**Comment by tillkamppeter** [comment]
No change:
[log-20200211-2.txt](https://github.com/OpenPrinting/ippusbxd/files/4187186/log-20200211-2.txt)

**Comment by ThierryHFR** [comment]
In capabilities.c, can you change that:
```
#define SIZE_DATA 32784
```
at 
```
#define SIZE_DATA 1024
```

**Comment by tillkamppeter** [comment]
Here we go:
[log-20200211-3.txt](https://github.com/OpenPrinting/ippusbxd/files/4187228/log-20200211-3.txt)

**Comment by ThierryHFR** [comment]
Okay, I'll look or I make a mistake using cups.

**Comment by ThierryHFR** [comment]
Can you send me the capabilities file  ?
curl http://127.0.0.1:60000/eSCL/ScannerCapabilities > capabilities.xml

**Comment by tillkamppeter** [comment]
[capabilities.xml.txt](https://github.com/OpenPrinting/ippusbxd/files/4187581/capabilities.xml.txt)

**Comment by ThierryHFR** [comment]
Can you execute this code and send me the result ?
```
mv getCapabilities.txt getCapabilities.c
gcc -o getCapabilities getCapabilities.txt $(pkg-config --libs --cflags libxml-2.0) -lcups -g
./getCapabilities 127.0.0.1 60000 > capabilites.txt
```
[getCapabilities.txt](https://github.com/OpenPrinting/ippusbxd/files/4187935/getCapabilities.txt)

**Comment by tillkamppeter** [comment]
Here is the result:
[capabilites.txt](https://github.com/OpenPrinting/ippusbxd/files/4187980/capabilites.txt)

**Pull request merged**
