### PR TITLE
Update capabilities.c

### PR DESCRIPTION
**Pull request by ThierryHFR**
Fix the value of the property color.

### CODE REVIEW

**Comment by ThierryHFR** [comment]
I don't have a duplex scanner handy, I'll look at it tomorrow and correct it for duplex.

**Comment by tillkamppeter** [comment]
Note that what I meant in the issue is not the scanner's duplex but the printer's duplex. I compared only the printer's TXT record for network, ippusbxd, and ipp-usb.

**Comment by ThierryHFR** [comment]
Ok, I debugged and I saw no error :)
ippinfo.c is the function in the capabilites.c file, from ippusbxd, that I use to report printer info.

**Comment by ThierryHFR** [comment]
Ok this is the property that tells me that the printer provided duplex : 
     sides-supported=two-sided-long-edge,two-sided-short-edge,one-sided

**Pull request merged**
