### PR TITLE
Add entry _uscan._tcp

### PR DESCRIPTION
**Pull request by ThierryHFR**
Since version 1.4 AirPrint, all multifunction devices implement the AirScan. My question is simple (I'm on vacation, I can't test), isn't a modification like this enough?

### CODE REVIEW

**Comment by tillkamppeter** [comment]
See discussion on Ordissimo@efe26ec, the original place where this patch got posted. Problem is that the patch simply adds a hard-coded DNS-SD record for a scanner function in the USB device, regardless whether there is actually one or not.

**Comment by ThierryHFR** [comment]
When I get back from my vacation, I'll see how to detect the scanner on the usb.
The only thing used to detect the scanner on the DNS-SD record is the field "rs=eSCL", the rest is not used.

**Comment by tillkamppeter** [comment]
There is a way to find out via pure USB whether there is a scanner at least. It is described in the [official IPP-over-USB documentation](https://www.usb.org/document-library/ipp-protocol-10). Download the `IPP.zip` file via the blue button at the upper right and unzip it. Therein you will find `IPP/IPP USB Specification.pdf`. In the file go to the section 4 ("Descriptors") and here especially 4.3 ("Device Info Descriptor") and see especially the table in the end. It should be possible to poll this descriptor with libusb functions (`lsusb -vvv` or `usbview` do not show it, unfortunately).
This way you can at least determine whether there is a scanner or not, and in case the printer supports AirPrint you can assume the scanner supporting AirScan and then advertise it (with basic TXT record telling about presence of eSCL resource).
Fur further differentiation (scan-only device, eSCL and/or IPP scanning, ...) most probably one or more HTTP/IPP polls of the device is needed, for example checking presence of ipp/print, ipp/scan, and eSCL resources, full capabilities request for better description in the TXT record for both printing and scanning (duplex, ADF, ...), IPP System Service support, ...

**Comment by ThierryHFR** [comment]
Thank you for info😁

**Comment by tillkamppeter** [comment]
@Ordissimo, thank you very much for the quick patch. There is only one small issue: What are you inserting for the scanner's PDLs in the TXT record? Note that the scanner's PDLs have nothing to do with the same device's printer's PDLs. For the scanner we use simply image/jpeg for now.

**Comment by ThierryHFR** [comment]
@tillkamppeter : I'll put in "pdl=image/jpeg".
It doesn't matter, I use the capabilities provided by the scanner.
For info the png and the tiff are being validated.
I finish the integration of the pdf.

**Comment by tillkamppeter** [comment]
Thenk you very much, @Ordissimo, I have merged your patch now. I will test it.

**Comment by tillkamppeter** [comment]
I have built ippusbxd with your changes and it does not discover the scanner in my DeskJet 2540. In the debug output of `ippusbxd -d` it says "-> Scanner present 0" right after discovering the USB interfaces. I get the same result both when starting ippusbxd as normal user and as root.

**Pull request merged**
