### PR TITLE
WIP Detect if scanner present and add a txt record for eSCL scanner.

### PR DESCRIPTION
**Pull request by ThierryHFR**

### CODE REVIEW

**Comment by ThierryHFR** [comment]
I didn't test it. I don't know if I put it" in the right place. I'm seeing it tonight!

**Comment by tillkamppeter** [comment]
Great, thank you very much.
Could you also make the TXT record for printing based on a get-printer-attributes IPP request and advertising of a web interface depend on wgether the get-printer-attributes IPP response has an "adminurl" entry?

**Comment by tillkamppeter** [comment]
It does not build:
```
$ make
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so  
-- Checking for module 'libcurl'
--   Found libcurl, version 7.66.0
-- Found Curl: /usr/lib/x86_64-linux-gnu/libcurl.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/till/printing/openprinting/ippusbxd/x/exe
Scanning dependencies of target ippusbxd
[ 12%] Building C object CMakeFiles/ippusbxd.dir/ippusbxd.c.o
[ 25%] Building C object CMakeFiles/ippusbxd.dir/http.c.o
[ 37%] Building C object CMakeFiles/ippusbxd.dir/tcp.c.o
[ 50%] Building C object CMakeFiles/ippusbxd.dir/usb.c.o
[ 62%] Building C object CMakeFiles/ippusbxd.dir/logging.c.o
[ 75%] Building C object CMakeFiles/ippusbxd.dir/options.c.o
[ 87%] Building C object CMakeFiles/ippusbxd.dir/dnssd.c.o
[100%] Linking C executable ippusbxd
/usr/bin/ld: CMakeFiles/ippusbxd.dir/dnssd.c.o: in function `dnssd_register':
/home/till/printing/openprinting/ippusbxd/x/src/dnssd.c:474: undefined reference to `is_scanner_present'
/usr/bin/ld: /home/till/printing/openprinting/ippusbxd/x/src/dnssd.c:508: undefined reference to `free_scanner'
/usr/bin/ld: /home/till/printing/openprinting/ippusbxd/x/src/dnssd.c:534: undefined reference to `free_scanner'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/ippusbxd.dir/build.make:179: ippusbxd] Error 1
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ippusbxd.dir/all] Error 2
make[1]: *** [Makefile:84: all] Error 2
make: *** [makefile:18: all] Error 2
$
```

**Comment by tillkamppeter** [comment]
Thank you, with your PR #18 it builds now.

**Comment by tillkamppeter** [comment]
But it does not detect my scanner:
```
ippusbxd --debug
<-1119132160>Note: Searching for first IPP-over-USB-capable device available
<-1119132160>Note: Found device: VID 0b95, PID 1790 on Bus 002, Device 002
<-1119132160>Note: Device connected on bus 002 device 002
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 255, Subclass 255, Protocol 0
<-1119132160>Note:    -> 0 Interfaces
<-1119132160>Note: Found device: VID 1d6b, PID 0003 on Bus 002, Device 001
<-1119132160>Note: Device connected on bus 002 device 001
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 9, Subclass 0, Protocol 0
<-1119132160>Note:    -> 0 Interfaces
<-1119132160>Note: Found device: VID 138a, PID 0097 on Bus 001, Device 005
<-1119132160>Note: Device connected on bus 001 device 005
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 255, Subclass 0, Protocol 0
<-1119132160>Note:    -> 0 Interfaces
<-1119132160>Note: Found device: VID 04f2, PID b5ce on Bus 001, Device 004
<-1119132160>Note: Device connected on bus 001 device 004
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 14, Subclass 1, Protocol 0
<-1119132160>Note: Interface 1, Alt 0: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 1: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 2: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 3: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 4: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 5: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 6: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 7: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 8: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 9: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 10: Class 14, Subclass 2, Protocol 0
<-1119132160>Note: Interface 1, Alt 11: Class 14, Subclass 2, Protocol 0
<-1119132160>Note:    -> 0 Interfaces
<-1119132160>Note: Found device: VID 8087, PID 0a2b on Bus 001, Device 003
<-1119132160>Note: Device connected on bus 001 device 003
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 224, Subclass 1, Protocol 1
<-1119132160>Note: Interface 1, Alt 0: Class 224, Subclass 1, Protocol 1
<-1119132160>Note: Interface 1, Alt 1: Class 224, Subclass 1, Protocol 1
<-1119132160>Note: Interface 1, Alt 2: Class 224, Subclass 1, Protocol 1
<-1119132160>Note: Interface 1, Alt 3: Class 224, Subclass 1, Protocol 1
<-1119132160>Note: Interface 1, Alt 4: Class 224, Subclass 1, Protocol 1
<-1119132160>Note: Interface 1, Alt 5: Class 224, Subclass 1, Protocol 1
<-1119132160>Note:    -> 0 Interfaces
<-1119132160>Note: Found device: VID 056a, PID 50b7 on Bus 001, Device 006
<-1119132160>Note: Device connected on bus 001 device 006
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 3, Subclass 0, Protocol 0
<-1119132160>Note: Interface 1, Alt 0: Class 3, Subclass 0, Protocol 0
<-1119132160>Note:    -> 0 Interfaces
<-1119132160>Note: Found device: VID 03f0, PID 7a12 on Bus 001, Device 029
<-1119132160>Note: Device connected on bus 001 device 029
<-1119132160>Note: Counting IPP-over-USB interfaces ...
<-1119132160>Note: Interface 0, Alt 0: Class 255, Subclass 204, Protocol 0
<-1119132160>Note: Interface 0, Alt 1: Class 7, Subclass 1, Protocol 4
<-1119132160>Note:    -> is IPP-over-USB
<-1119132160>Note: Interface 1, Alt 0: Class 7, Subclass 1, Protocol 2
<-1119132160>Note: Interface 2, Alt 0: Class 255, Subclass 4, Protocol 1
<-1119132160>Note: Interface 2, Alt 1: Class 7, Subclass 1, Protocol 4
<-1119132160>Note:    -> is IPP-over-USB
<-1119132160>Note: Interface 3, Alt 0: Class 255, Subclass 255, Protocol 0
<-1119132160>Note: Interface 4, Alt 0: Class 255, Subclass 4, Protocol 1
<-1119132160>Note: Interface 4, Alt 1: Class 7, Subclass 1, Protocol 4
<-1119132160>Note:    -> is IPP-over-USB
<-1119132160>Note:    -> 3 Interfaces
<-1119132160>Note: Could not retrieve device ID for config #0, interface #0, alt setting #0, will try with other combo ...
<-1119132160>Note: USB device ID: MFG:HP;MDL:HP OfficeJet Pro 8730;CMD:PCL5c,PCLXL,POSTSCRIPT,NATIVEOFFICE,PDF,PCL3GUI,PCL3,PJL,Automatic,JPEG,PCLM,AppleRaster,PWGRaster,802.11,802.3,DESKJET,DYN;CLS:PRINTER;DES:D9L20A;CID:HPIJVIPAV9;LEDMDIS:USB#FF#CC#00,USB#FF#04#01;MCT:MF;MCL:DI;MCV:3.0;SN:CN783F60W1;S:038080C484100001005800800004418003c451800464618003c41180046;Z:05000009000009000009000009000009,12000,17000000000000000000000000000000,181;
<-1119132160>Note: USB interfaces pool: 3 interfaces
<-1119132160>Note: IPv4: Binding to 127.0.0.1:60000
<-1119132160>Note: IPv6: Binding to [::1]:60000
60000|<-1119132160>Note: Port: 60000, IPv4 available, IPv6 available
<-1119132160>Note: Using signal handler SIGNAL
<-1119132160>Note: Registered unplug callback
<-1127540992>Note: USB unplug event observer thread starting
<-1119132160>Note: Avahi server connection got available, registering printer.
<-1119132160>Note: No URF info in device ID
<-1119132160>Note: Registering printer HP OfficeJet Pro 8730 [CN783F60W1] on interface lo for DNS-SD broadcasting ...
<-1119132160>Note: Registered HP OfficeJet Pro 8730 [CN783F60W1] as Unix printer (_printer._tcp).
<-1119132160>Note: Registered HP OfficeJet Pro 8730 [CN783F60W1] as IPP printer (_ipp._tcp).
<-1119132160>Note: Registered subtype for IPP printer HP OfficeJet Pro 8730 [CN783F60W1] (_print._sub._ipp._tcp or _universal._sub._ipp._tcp).
<-1119132160>Note: Registered web interface of HP OfficeJet Pro 8730 [CN783F60W1] (_http._tcp).
<-1119132160>Note: Registered subtype for web interface of HP OfficeJet Pro 8730 [CN783F60W1] (_printer._sub._http._tcp).
<-1119132160>Note: DNS-SD initialized.
<-1135933696>Note: Service entry for the printer successfully established.
<-1119132160>Note: Using IPv6
<-1119132160>Note: Registering thread #1
<-1119132160>Note: Threads currently running: #1
<-1144326400>Note: Registering thread #2
<-1144326400>Note: Threads currently running: #1, #2
<-1144326400>Note: Thread #1: Pkt from tcp (buffer size: 397)
===
  00000000  50 4f 53 54 20 2f 69 70 70 2f 70 72 69 6e 74 20  POST /ipp/print 
  00000010  48 54 54 50 2f 31 2e 31 0d 0a 43 6f 6e 74 65 6e  HTTP/1.1..Conten
  00000020  74 2d 4c 65 6e 67 74 68 3a 20 31 37 30 0d 0a 43  t-Length: 170..C
  00000030  6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70  ontent-Type: app
  00000040  6c 69 63 61 74 69 6f 6e 2f 69 70 70 0d 0a 44 61  lication/ipp..Da
  00000050  74 65 3a 20 54 68 75 2c 20 30 36 20 46 65 62 20  te: Thu, 06 Feb 
  00000060  32 30 32 30 20 31 37 3a 30 32 3a 32 36 20 47 4d  2020 17:02:26 GM
  00000070  54 0d 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f  T..Host: localho
  00000080  73 74 3a 36 30 30 30 30 0d 0a 55 73 65 72 2d 41  st:60000..User-A
  00000090  67 65 6e 74 3a 20 43 55 50 53 2f 32 2e 33 2e 31  gent: CUPS/2.3.1
  000000a0  20 28 4c 69 6e 75 78 20 35 2e 34 2e 30 2d 31 32   (Linux 5.4.0-12
  000000b0  2d 67 65 6e 65 72 69 63 3b 20 78 38 36 5f 36 34  -generic; x86_64
  000000c0  29 20 49 50 50 2f 32 2e 30 0d 0a 45 78 70 65 63  ) IPP/2.0..Expec
  000000d0  74 3a 20 31 30 30 2d 63 6f 6e 74 69 6e 75 65 0d  t: 100-continue.
  000000e0  0a 0d 0a 02 00 00 0b 00 00 04 27 01 47 00 12 61  ..........'.G..a
  000000f0  74 74 72 69 62 75 74 65 73 2d 63 68 61 72 73 65  ttributes-charse
  00000100  74 00 05 75 74 66 2d 38 48 00 1b 61 74 74 72 69  t..utf-8H..attri
  00000110  62 75 74 65 73 2d 6e 61 74 75 72 61 6c 2d 6c 61  butes-natural-la
  00000120  6e 67 75 61 67 65 00 02 65 6e 45 00 0b 70 72 69  nguage..enE..pri
  00000130  6e 74 65 72 2d 75 72 69 00 1f 69 70 70 3a 2f 2f  nter-uri..ipp://
  00000140  6c 6f 63 61 6c 68 6f 73 74 3a 36 30 30 30 30 2f  localhost:60000/
  00000150  69 70 70 2f 70 72 69 6e 74 44 00 14 72 65 71 75  ipp/printD..requ
  00000160  65 73 74 65 64 2d 61 74 74 72 69 62 75 74 65 73  ested-attributes
  00000170  00 03 61 6c 6c 44 00 00 00 12 6d 65 64 69 61 2d  ..allD....media-
  00000180  63 6f 6c 2d 64 61 74 61 62 61 73 65 03           col-database.
===
<-1144326400>Note: P 0x7f2fac000d00: USB: want to send 397 bytes
<-1144326400>Note: P 0x7f2fac000d00: USB: sent 397 bytes
<-1144326400>Note: P 0x7f2fac000d00: USB: sent 397 bytes in total
<-1127540992>Note: Thread #2: Pkt from usb (buffer size: 252)
===
  00000000  48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d  HTTP/1.1 200 OK.
  00000010  0a 53 65 72 76 65 72 3a 20 48 50 20 48 54 54 50  .Server: HP HTTP
  00000020  20 53 65 72 76 65 72 3b 20 48 50 20 4f 66 66 69   Server; HP Offi
  00000030  63 65 4a 65 74 20 50 72 6f 20 38 37 33 30 20 2d  ceJet Pro 8730 -
  00000040  20 44 39 4c 32 30 41 3b 20 53 65 72 69 61 6c 20   D9L20A; Serial 
  00000050  4e 75 6d 62 65 72 3a 20 43 4e 37 38 33 46 36 30  Number: CN783F60
  00000060  57 31 3b 20 42 75 69 6c 74 3a 20 46 72 69 20 4d  W1; Built: Fri M
  00000070  61 79 20 31 30 2c 20 32 30 31 39 20 30 31 3a 33  ay 10, 2019 01:3
  00000080  32 3a 31 34 50 4d 20 7b 57 45 42 50 44 4c 50 50  2:14PM {WEBPDLPP
  00000090  31 4e 30 30 31 2e 31 39 31 39 41 2e 30 30 7d 0d  1N001.1919A.00}.
  000000a0  0a 54 72 61 6e 73 66 65 72 2d 45 6e 63 6f 64 69  .Transfer-Encodi
  000000b0  6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 43 61 63  ng: chunked..Cac
  000000c0  68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 6d 75 73 74  he-Control: must
  000000d0  2d 72 65 76 61 6c 69 64 61 74 65 2c 20 6d 61 78  -revalidate, max
  000000e0  2d 61 67 65 3d 30 0d 0a 50 72 61 67 6d 61 3a 20  -age=0..Pragma: 
  000000f0  6e 6f 2d 63 61 63 68 65 0d 0a 0d 0a              no-cache....
===
<-1127540992>Note: TCP: sent 252 bytes
<-1127540992>Note: Thread #2: Pkt from usb (buffer size: 6)
===
  00000000  33 38 30 41 0d 0a                                380A..
===
[...]
```

**Comment by ThierryHFR** [comment]
I suspected that placing it there would be too simple, the add function recovers the capabilities of the scanner, after that you have to add the recording.
I see where to do it tonight, the main thing is there :)

**Comment by ThierryHFR** [comment]
Hi @tillkamppeter,
I finally got the txt recording to work, for the scanner.
I'm trying to finalize it tomorrow!

**Comment by ThierryHFR** [comment]
Le 2020-02-06 17:38, Till Kamppeter a écrit :
> Great, thank you very much.
> Could you also make the TXT record for printing based on a
> get-printer-attributes IPP request and advertising of a web interface
> depend on wgether the get-printer-attributes IPP response has an
> "adminurl" entry?
Hi Till,
I've added all the fields for an eSCL scanner, that includes the 
adminurl field, is that what you're talking about?
Thierry

**Comment by tillkamppeter** [comment]
Now it is only needed that after establishing the USB connection you do a get-printer-attributes IPP request on the printing part and a ScannerCapabilities request on the scanning part of the device to generate the correct TXT records based on the results.

**Comment by ThierryHFR** [comment]
Le 2020-02-09 16:38, Till Kamppeter a écrit :
> Now it is only needed that after establishing the USB connection you
> do a get-printer-attributes IPP request on the printing part and a
> ScannerCapabilities request on the scanning part of the device to
> generate the correct TXT records based on the results.
This is what is done for the scanner part in: 
https://github.com/OpenPrinting/ippusbxd/pull/20.

**Comment by tillkamppeter** [comment]
I have merged this PR, pulled it, done "make", started ippusbxd and only the printer of my device got advertised.

**Comment by ThierryHFR** [comment]
Le 2020-02-09 16:53, Till Kamppeter a écrit :
> I have merged this PR, pulled it, done "make", started ippusbxd and
> only the printer of my device got advertised.

can you give me the result of ippusbxd --debug

**Comment by ThierryHFR** [comment]
Le 2020-02-09 16:56, Thierry HUCAHRD a écrit :
> Le 2020-02-09 16:53, Till Kamppeter a écrit :
>> I have merged this PR, pulled it, done "make", started ippusbxd and
>> only the printer of my device got advertised.
> 
> can you give me the result of ippusbxd --debug

My Avahi record :
+     lo IPv4 DCP-L2530DW series                            UNIX Printer 
         local
+     lo IPv4 DCP-L2530DW series                            Internet 
Printer     local
+     lo IPv4 DCP-L2530DW series                            Web Site     
         local
=     lo IPv4 DCP-L2530DW series                            UNIX Printer 
         local
    hostname = [localhost]
    address = [127.0.0.1]
    port = [0]
    txt = []
=     lo IPv4 DCP-L2530DW series                            Internet 
Printer     local
    hostname = [localhost]
    address = [127.0.0.1]
    port = [60000]
    txt = ["qtotal=1" "txtvers=1" "priority=60" 
"URF=W8,CP1,IS4-1,MT1-3-4-5-8,OB10,PQ3-4-5,RS300-600-1200,V1.4,DM1" 
"usb_MDL=DCP-L2530DW series" "usb_MFG=Brother" "Copies=F" "Duplex=T" 
"Color=F" "pdl=image/urf" "product=(DCP-L2530DW series)" 
"adminurl=http://localhost:60000/" "ty=Brother DCP-L2530DW series" 
"rp=ipp/print"]
=     lo IPv4 DCP-L2530DW series                            Web Site     
         local
    hostname = [localhost]
    address = [127.0.0.1]
    port = [60000]
    txt = []
+     lo IPv4 Brother DCP-L2530DW series                    _uscan._tcp  
         local
=     lo IPv4 Brother DCP-L2530DW series                    _uscan._tcp  
         local
    hostname = [localhost]
    address = [127.0.0.1]
    port = [60000]
    txt = ["txtvers=1" "vers=2.63" "rs=eSCL" "ty=Brother DCP-L2530DW 
series" "pdl=application/pdf,image/jpeg" "cs=binary,grayscale,color" 
"dupplex=F" "adminurl=http://127.0.0.1:60000/net/net/airprint.html" 
"UUID=e3248000-80ce-11db-8000-c0b5d7e62277" "note=" 
"representation=http://127.0.0.1:60000/icons/device-icons-128.png"]

**Comment by tillkamppeter** [comment]
Sorry, I had started the wrong executable. Now my scanner detection works and I am able to scan with simple-scan.
Only the TXT record is somewhat broken. I get
```
txt = [
"representation=(null)"
"note="
"UUID=(null)"
"adminurl=(null)"
"duplex=T"
"is=platen,adf"
"cs=grayscale,color"
"pdl=application/octet-stream,image/jpeg,application/pdf"
"ty=HP OfficeJet Pro 8730"
"rs=eSCL"
"vers=2.5"
"txtvers=1"
]
```
Note that "representation", "UUID", and "adminurl" get "(null)" in the TXT record. This makes it somewhat broken.
And the service name should contain a unique identifier of the device, like the service name of the device on the network (allows to use more than one device of the same model) and "(USB)" (so that one can distinguish USB and network access, especially important for confidential documents as USB is more secure).
ipp-usb advertises my device as follows:
```
HP OfficeJet Pro 8730 [08C229] (USB)
```

**Comment by tillkamppeter** [comment]
Here is the debug log:
[ippusbxd-log-20200102.txt](https://github.com/OpenPrinting/ippusbxd/files/4177162/ippusbxd-log-20200102.txt)

**Comment by tillkamppeter** [comment]
I am still floating around in my system and trying.
Hope this one is right:
[log-20200209.txt](https://github.com/OpenPrinting/ippusbxd/files/4177164/log-20200209.txt)

**Pull request merged**
