### PR TITLE
WIP : Escl detect

### PR DESCRIPTION
**Pull request by ThierryHFR**
Hi @tillkamppeter 
the ipptousb script starts publishing TXT records for the printer and scanner. 
I need to make the script launch by udev more reliable.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Why are you creating a second daemon for the scanner? It is so easy to let the already existing ippusbxd send some requests to the device to check the resources /ipp/print and /eSCL and then depending on the result register the printing and scanning part. See the ipp-usb project. Also if you have two daemons running which both do IPP-over-USB how do they do it without conflicts?
Also if the second daemon is only doing the scanner's DNS-SD registration, why an extra daemon for that. The existing ippusbxd already handles Avahi, so that running a second daemon doing only Avahi is not really needed.

**Comment by ThierryHFR** [comment]
Hi @tillkamppeter,
Only the ippusbxd daemon uses ipp-over-usb. The second adds only the escl record.
I put WIP to indicate that I was working.
But in order to be able to ask the scanner about its capabilities, ippusbxd has to be launched.
The ideal would be to launch the information request in in thread, for the moment, I failed. I'm working on solving the problem.

**Comment by tillkamppeter** [comment]
What you need to do in ippusbxd is to first establish the USB connection, then request the scanner (and printer) capabilities from the device. You can send directly to the USB channels, do not need to go though the TCP part, and will get the answer directly from the USB channel. After that you register on Avahi with the actual scanner (and printer) capabilities of the device.

**Comment by ThierryHFR** [comment]
Fixed in https://github.com/OpenPrinting/ippusbxd/pull/20

**Pull request closed without merging**
